language: python
python:
    - "3.7"

install:
    - pip install -e .
    - pip install pytest-cov codecov # Install packcages for code coverage report
script:
    - pytest --cov=src test # Point to the source directory